### ISSUE TITLE
More description

### ISSUE THREAD

**Issue by compgeniuses** [eust-w/esh#1]
Could you be abit more descriptive on this tool, how it works and what its trying to acheive kindly.

Been tryign to understand this bit with no success

**Comment by eust-w** [comment]
Hello,

Thank you for your interest in esh! I'd be happy to provide more details about the tool, how it works, and its goals.

What is esh?
esh is a cross-platform SSH link management tool designed to simplify and streamline the process of managing multiple SSH connections. It is particularly useful for developers and system administrators who frequently connect to various remote servers.

How does esh work?
Installation:

You can install esh from the source or download precompiled binaries for different platforms (Linux, Mac, Windows).
After downloading, you can run the executable directly from the command line.
Command Descriptions:

add: Add a new remote SSH connection by specifying the necessary details (e.g., hostname, username, password).
cluster: Use this command to connect to remote SSH or execute commands across multiple SSH connections simultaneously.
completion: Generate autocompletion scripts for your shell to make it easier to use esh commands.
del: Delete an existing SSH connection using its name.
help: Get detailed information about any esh command.
list: List all the remote SSH connections you have added.
run: Connect to a remote SSH or run a command on it.
set: Configure global settings for esh.
What is esh trying to achieve?
esh aims to provide a powerful yet user-friendly tool for managing SSH connections. Its key features include:

Centralized Management: Easily add, list, delete, and configure SSH connections from a single interface.
Security: Encrypts passwords and usernames/IP addresses using AES encryption, ensuring your credentials are protected.
Convenience: Supports autocompletion, making it quicker to enter commands. It also has features like login auto-completion and key-based login for added security.
Automation: Run commands on multiple remote servers simultaneously, which is particularly useful for managing clusters.
Development and Configuration
esh reads configuration information from Home/esh_config.yaml.
It supports AES encryption for passwords and usernames/IPs, with at least two AES keys for encryption and decryption.
Decryption is based on the initial identifier, allowing secure storage and retrieval of credentials.
Root accounts can view plaintext passwords, with the password being a salted value compiled at build time.
It supports login auto-completion and requires entering a key for login, ensuring secure access.
esh can execute remote commands like SSH and supports cluster functionality, making it a versatile tool for various administrative tasks.
I hope this provides a clearer understanding of esh and its capabilities. If you have any more questions or need further clarification, feel free to ask!

**Comment by compgeniuses** [comment]
This is a way more descriptive and better desctipion.

Kindly consider adding to the MAin README for others

**Comment by eust-w** [comment]
Hi @compgeniuses,

Thank you for your feedback! I'm glad you found the description clearer. We will consider adding this information to the main README to benefit other users. If you have the time, you could also submit a PR to make this update. It would be greatly appreciated!

Thanks for your support!

**Comment by compgeniuses** [comment]
Done #3
